import type { TarotCard } from "../types/tarot";

const rwsFileById: Record<string, string> = {
  fool: "RWS Tarot 00 Fool.jpg",
  magician: "RWS Tarot 01 Magician.jpg",
  "high-priestess": "RWS Tarot 02 High Priestess.jpg",
  empress: "RWS Tarot 03 Empress.jpg",
  emperor: "RWS Tarot 04 Emperor.jpg",
  hierophant: "RWS Tarot 05 Hierophant.jpg",
  lovers: "RWS Tarot 06 Lovers.jpg",
  chariot: "RWS Tarot 07 Chariot.jpg",
  strength: "RWS Tarot 08 Strength.jpg",
  hermit: "RWS Tarot 09 Hermit.jpg",
  wheel: "RWS Tarot 10 Wheel of Fortune.jpg",
  justice: "RWS Tarot 11 Justice.jpg",
  "hanged-man": "RWS Tarot 12 Hanged Man.jpg",
  death: "RWS Tarot 13 Death.jpg",
  temperance: "RWS Tarot 14 Temperance.jpg",
  devil: "RWS Tarot 15 Devil.jpg",
  tower: "RWS Tarot 16 Tower.jpg",
  star: "RWS Tarot 17 Star.jpg",
  moon: "RWS Tarot 18 Moon.jpg",
  sun: "RWS Tarot 19 Sun.jpg",
  judgement: "RWS Tarot 20 Judgement.jpg",
  world: "RWS Tarot 21 World.jpg",
  "wands-ace": "Wands01.jpg",
  "wands-two": "Wands02.jpg",
  "wands-three": "Wands03.jpg",
  "wands-four": "Wands04.jpg",
  "wands-five": "Wands05.jpg",
  "wands-six": "Wands06.jpg",
  "wands-seven": "Wands07.jpg",
  "wands-eight": "Wands08.jpg",
  "wands-nine": "Wands09.jpg",
  "wands-ten": "Wands10.jpg",
  "wands-page": "Wands11.jpg",
  "wands-knight": "Wands12.jpg",
  "wands-queen": "Wands13.jpg",
  "wands-king": "Wands14.jpg",
  "cups-ace": "Cups01.jpg",
  "cups-two": "Cups02.jpg",
  "cups-three": "Cups03.jpg",
  "cups-four": "Cups04.jpg",
  "cups-five": "Cups05.jpg",
  "cups-six": "Cups06.jpg",
  "cups-seven": "Cups07.jpg",
  "cups-eight": "Cups08.jpg",
  "cups-nine": "Cups09.jpg",
  "cups-ten": "Cups10.jpg",
  "cups-page": "Cups11.jpg",
  "cups-knight": "Cups12.jpg",
  "cups-queen": "Cups13.jpg",
  "cups-king": "Cups14.jpg",
  "swords-ace": "Swords01.jpg",
  "swords-two": "Swords02.jpg",
  "swords-three": "Swords03.jpg",
  "swords-four": "Swords04.jpg",
  "swords-five": "Swords05.jpg",
  "swords-six": "Swords06.jpg",
  "swords-seven": "Swords07.jpg",
  "swords-eight": "Swords08.jpg",
  "swords-nine": "Swords09.jpg",
  "swords-ten": "Swords10.jpg",
  "swords-page": "Swords11.jpg",
  "swords-knight": "Swords12.jpg",
  "swords-queen": "Swords13.jpg",
  "swords-king": "Swords14.jpg",
  "pentacles-ace": "Pents01.jpg",
  "pentacles-two": "Pents02.jpg",
  "pentacles-three": "Pents03.jpg",
  "pentacles-four": "Pents04.jpg",
  "pentacles-five": "Pents05.jpg",
  "pentacles-six": "Pents06.jpg",
  "pentacles-seven": "Pents07.jpg",
  "pentacles-eight": "Pents08.jpg",
  "pentacles-nine": "Pents09.jpg",
  "pentacles-ten": "Pents10.jpg",
  "pentacles-page": "Pents11.jpg",
  "pentacles-knight": "Pents12.jpg",
  "pentacles-queen": "Pents13.jpg",
  "pentacles-king": "Pents14.jpg",
};

function rwsImageUrl(cardId: string) {
  return `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(
    rwsFileById[cardId],
  )}?width=420`;
}

const tarotCards: TarotCard[] = [
  { id: "fool", name: "The Fool", zhName: "愚者", image: "✦", meanings: { upright: "新的开始、信任直觉、轻装上路。", reversed: "冲动、准备不足、忽略现实边界。" } },
  { id: "magician", name: "The Magician", zhName: "魔术师", image: "☿", meanings: { upright: "资源到位、主动创造、把想法落地。", reversed: "能量分散、表达失真、尚未对齐目标。" } },
  { id: "high-priestess", name: "The High Priestess", zhName: "女祭司", image: "☾", meanings: { upright: "内在智慧、直觉、暂时保持观察。", reversed: "压抑感受、信息不清、过度猜测。" } },
  { id: "empress", name: "The Empress", zhName: "女皇", image: "✺", meanings: { upright: "滋养、丰盛、关系和创作的生长。", reversed: "消耗、过度照顾、缺少自我滋养。" } },
  { id: "emperor", name: "The Emperor", zhName: "皇帝", image: "♜", meanings: { upright: "秩序、责任、建立稳定结构。", reversed: "控制感过强、僵化、权责不清。" } },
  { id: "hierophant", name: "The Hierophant", zhName: "教皇", image: "✠", meanings: { upright: "传统、指引、从经验和规则中获得支持。", reversed: "僵化信念、过度服从、需要重新定义自己的标准。" } },
  { id: "lovers", name: "The Lovers", zhName: "恋人", image: "♡", meanings: { upright: "选择、联结、价值观对齐。", reversed: "摇摆、关系失衡、真实需求被回避。" } },
  { id: "chariot", name: "The Chariot", zhName: "战车", image: "◆", meanings: { upright: "意志、推进、在拉扯中保持方向。", reversed: "失控、急于证明、节奏被外界带走。" } },
  { id: "strength", name: "Strength", zhName: "力量", image: "♌", meanings: { upright: "温柔的勇气、自我安抚、持续行动。", reversed: "自我怀疑、压抑怒气、能量透支。" } },
  { id: "hermit", name: "The Hermit", zhName: "隐士", image: "✧", meanings: { upright: "独处、内省、寻找真正的答案。", reversed: "孤立、逃避交流、陷入反复思考。" } },
  { id: "wheel", name: "Wheel of Fortune", zhName: "命运之轮", image: "◎", meanings: { upright: "转机、周期变化、顺势调整。", reversed: "抗拒变化、重复旧模式、时机未稳。" } },
  { id: "justice", name: "Justice", zhName: "正义", image: "⚖", meanings: { upright: "公平、因果、清楚承担选择的后果。", reversed: "失衡、逃避责任、判断被偏见影响。" } },
  { id: "hanged-man", name: "The Hanged Man", zhName: "倒吊人", image: "♆", meanings: { upright: "暂停、换个角度、在等待中获得理解。", reversed: "无谓牺牲、停滞不前、不愿放下旧姿态。" } },
  { id: "death", name: "Death", zhName: "死神", image: "✝", meanings: { upright: "结束、转化、为新阶段腾出空间。", reversed: "抗拒结束、拖延改变、旧问题反复回来。" } },
  { id: "temperance", name: "Temperance", zhName: "节制", image: "♒", meanings: { upright: "调和、耐心、把不同力量重新配平。", reversed: "过度、失调、节奏需要重新校准。" } },
  { id: "devil", name: "The Devil", zhName: "恶魔", image: "♑", meanings: { upright: "执着、诱惑、看见束缚自己的模式。", reversed: "松绑、觉察依赖、从消耗关系中抽离。" } },
  { id: "tower", name: "The Tower", zhName: "高塔", image: "⌁", meanings: { upright: "突变、真相显露、旧结构被迫瓦解。", reversed: "延迟爆发、害怕失控、需要主动拆除隐患。" } },
  { id: "star", name: "The Star", zhName: "星星", image: "✶", meanings: { upright: "希望、疗愈、重新相信未来。", reversed: "信心低落、期待落空、需要恢复感受力。" } },
  { id: "moon", name: "The Moon", zhName: "月亮", image: "☽", meanings: { upright: "潜意识、暧昧、看见恐惧背后的讯息。", reversed: "迷雾散去、误解浮现、情绪需要被命名。" } },
  { id: "sun", name: "The Sun", zhName: "太阳", image: "☉", meanings: { upright: "清晰、喜悦、事情走向更坦荡明亮。", reversed: "乐观不足、能量被遮挡、需要重新找回自信。" } },
  { id: "judgement", name: "Judgement", zhName: "审判", image: "♁", meanings: { upright: "觉醒、复盘、回应内心真正的召唤。", reversed: "自我否定、迟迟不愿面对结论、旧账未清。" } },
  { id: "world", name: "The World", zhName: "世界", image: "⊕", meanings: { upright: "完成、整合、阶段圆满并进入新循环。", reversed: "收尾不彻底、目标未闭合、还差最后一步。" } },

  { id: "wands-ace", name: "Ace of Wands", zhName: "权杖一", image: "W1", meanings: { upright: "灵感、行动火花、新计划开始燃起。", reversed: "热情不足、迟疑开局、点子还需要落地条件。" } },
  { id: "wands-two", name: "Two of Wands", zhName: "权杖二", image: "W2", meanings: { upright: "规划、远景、站在更大的视角做选择。", reversed: "犹豫不前、害怕扩展、计划停留在想象中。" } },
  { id: "wands-three", name: "Three of Wands", zhName: "权杖三", image: "W3", meanings: { upright: "等待成果、拓展机会、行动开始看见回响。", reversed: "进展延迟、视野受限、合作或外部条件未到位。" } },
  { id: "wands-four", name: "Four of Wands", zhName: "权杖四", image: "W4", meanings: { upright: "庆祝、稳定关系、阶段性安全感。", reversed: "归属感不足、庆祝被推迟、基础还不够稳。" } },
  { id: "wands-five", name: "Five of Wands", zhName: "权杖五", image: "W5", meanings: { upright: "竞争、摩擦、在碰撞中确认位置。", reversed: "内耗、避免冲突、表面平静下仍有拉扯。" } },
  { id: "wands-six", name: "Six of Wands", zhName: "权杖六", image: "W6", meanings: { upright: "认可、胜利、努力被看见。", reversed: "缺少肯定、骄傲受挫、需要把成果做得更扎实。" } },
  { id: "wands-seven", name: "Seven of Wands", zhName: "权杖七", image: "W7", meanings: { upright: "防守立场、坚持边界、面对压力仍不退让。", reversed: "疲惫防御、信心动摇、需要选择真正值得守的事。" } },
  { id: "wands-eight", name: "Eight of Wands", zhName: "权杖八", image: "W8", meanings: { upright: "快速推进、消息到来、事情进入加速期。", reversed: "延误、沟通卡住、行动太急反而失准。" } },
  { id: "wands-nine", name: "Nine of Wands", zhName: "权杖九", image: "W9", meanings: { upright: "韧性、警觉、最后一段路仍需坚持。", reversed: "过度戒备、身心透支、旧伤影响判断。" } },
  { id: "wands-ten", name: "Ten of Wands", zhName: "权杖十", image: "W10", meanings: { upright: "责任沉重、任务压身、快到终点但负担很大。", reversed: "卸下负担、拒绝过载、重新分配责任。" } },
  { id: "wands-page", name: "Page of Wands", zhName: "权杖侍从", image: "WP", meanings: { upright: "好奇、尝试、带着热情探索新方向。", reversed: "三分钟热度、经验不足、行动前需要更多准备。" } },
  { id: "wands-knight", name: "Knight of Wands", zhName: "权杖骑士", image: "WN", meanings: { upright: "冲劲、冒险、快速投入热爱的事。", reversed: "鲁莽、急躁、来得快去得也快。" } },
  { id: "wands-queen", name: "Queen of Wands", zhName: "权杖王后", image: "WQ", meanings: { upright: "自信、魅力、温暖而有主见的能量。", reversed: "自我怀疑、占有欲、外强中干。" } },
  { id: "wands-king", name: "King of Wands", zhName: "权杖国王", image: "WK", meanings: { upright: "领导力、愿景、把热情组织成方向。", reversed: "控制欲、急于掌控、愿景压过现实细节。" } },

  { id: "cups-ace", name: "Ace of Cups", zhName: "圣杯一", image: "C1", meanings: { upright: "情感开启、疗愈、心里有新的流动。", reversed: "情绪封闭、爱意受阻、需要先照顾自己。" } },
  { id: "cups-two", name: "Two of Cups", zhName: "圣杯二", image: "C2", meanings: { upright: "互相靠近、情感回应、关系建立连接。", reversed: "关系失衡、误解、期待没有对齐。" } },
  { id: "cups-three", name: "Three of Cups", zhName: "圣杯三", image: "C3", meanings: { upright: "支持、庆祝、朋友与社群带来滋养。", reversed: "圈层消耗、过度社交、关系里的边界混乱。" } },
  { id: "cups-four", name: "Four of Cups", zhName: "圣杯四", image: "C4", meanings: { upright: "倦怠、迟疑、对眼前机会暂时无感。", reversed: "重新打开心门、看见被忽略的选择。" } },
  { id: "cups-five", name: "Five of Cups", zhName: "圣杯五", image: "C5", meanings: { upright: "失落、遗憾、注意力停在已经失去的部分。", reversed: "走出遗憾、愿意修复、重新看见仍然拥有的东西。" } },
  { id: "cups-six", name: "Six of Cups", zhName: "圣杯六", image: "C6", meanings: { upright: "回忆、单纯、过去的人事带来温柔提醒。", reversed: "沉溺过去、旧模式拉扯、需要回到现在。" } },
  { id: "cups-seven", name: "Seven of Cups", zhName: "圣杯七", image: "C7", meanings: { upright: "想象、选择很多、需要分辨真实愿望。", reversed: "幻象散去、选择收窄、开始面对现实。" } },
  { id: "cups-eight", name: "Eight of Cups", zhName: "圣杯八", image: "C8", meanings: { upright: "离开、寻找更深意义、主动告别不满足。", reversed: "舍不得走、害怕空白、明知不适合仍停留。" } },
  { id: "cups-nine", name: "Nine of Cups", zhName: "圣杯九", image: "C9", meanings: { upright: "满足、愿望实现、情绪上获得丰盈。", reversed: "表面满足、空虚感、欲望和真实需求不一致。" } },
  { id: "cups-ten", name: "Ten of Cups", zhName: "圣杯十", image: "C10", meanings: { upright: "圆满关系、家庭感、情感上的长期安稳。", reversed: "理想落差、家庭或亲密关系里的不协调。" } },
  { id: "cups-page", name: "Page of Cups", zhName: "圣杯侍从", image: "CP", meanings: { upright: "柔软表达、好消息、情感上的新鲜萌动。", reversed: "情绪幼稚、表达含糊、敏感但不够稳定。" } },
  { id: "cups-knight", name: "Knight of Cups", zhName: "圣杯骑士", image: "CN", meanings: { upright: "浪漫、邀约、跟随内心靠近渴望。", reversed: "情绪化承诺、理想化、说得美但行动不足。" } },
  { id: "cups-queen", name: "Queen of Cups", zhName: "圣杯王后", image: "CQ", meanings: { upright: "共情、温柔、成熟地照看自己和他人的感受。", reversed: "情绪边界薄弱、过度代入、需要先回到自己。" } },
  { id: "cups-king", name: "King of Cups", zhName: "圣杯国王", image: "CK", meanings: { upright: "情绪成熟、包容、在风浪里保持稳定。", reversed: "压抑情绪、表面冷静、用控制掩盖不安。" } },

  { id: "swords-ace", name: "Ace of Swords", zhName: "宝剑一", image: "S1", meanings: { upright: "清晰、真相、用理性切开混乱。", reversed: "判断模糊、表达锋利、真相还没有完全浮现。" } },
  { id: "swords-two", name: "Two of Swords", zhName: "宝剑二", image: "S2", meanings: { upright: "僵持、回避选择、用冷静保护自己。", reversed: "防线松动、信息浮现、必须面对决定。" } },
  { id: "swords-three", name: "Three of Swords", zhName: "宝剑三", image: "S3", meanings: { upright: "心痛、失望、刺耳但真实的事实。", reversed: "疗伤、痛感减轻、开始从伤害中恢复。" } },
  { id: "swords-four", name: "Four of Swords", zhName: "宝剑四", image: "S4", meanings: { upright: "休息、暂停思考、恢复精神秩序。", reversed: "无法停下、焦虑反复、身体和心智都需要缓冲。" } },
  { id: "swords-five", name: "Five of Swords", zhName: "宝剑五", image: "S5", meanings: { upright: "争执、赢了表面却损耗关系。", reversed: "停止消耗、承认代价、寻找更体面的退路。" } },
  { id: "swords-six", name: "Six of Swords", zhName: "宝剑六", image: "S6", meanings: { upright: "过渡、离开混乱、慢慢去往更平静的地方。", reversed: "难以放下、迁移受阻、旧问题仍在船上。" } },
  { id: "swords-seven", name: "Seven of Swords", zhName: "宝剑七", image: "S7", meanings: { upright: "策略、隐瞒、需要小心信息不完整。", reversed: "真相泄露、计划失效、重新面对诚实问题。" } },
  { id: "swords-eight", name: "Eight of Swords", zhName: "宝剑八", image: "S8", meanings: { upright: "受困、限制感、被自己的想法困住。", reversed: "看见出口、限制松动、可以重新拿回选择权。" } },
  { id: "swords-nine", name: "Nine of Swords", zhName: "宝剑九", image: "S9", meanings: { upright: "焦虑、失眠、自责或担忧被放大。", reversed: "噩梦减弱、愿意求助、开始停止反复折磨自己。" } },
  { id: "swords-ten", name: "Ten of Swords", zhName: "宝剑十", image: "S10", meanings: { upright: "低谷、终结、痛苦已经到达尾声。", reversed: "复原、从崩塌中爬起、最难的部分正在过去。" } },
  { id: "swords-page", name: "Page of Swords", zhName: "宝剑侍从", image: "SP", meanings: { upright: "观察、学习、敏锐地捕捉信息。", reversed: "多疑、嘴快、信息未经确认就行动。" } },
  { id: "swords-knight", name: "Knight of Swords", zhName: "宝剑骑士", image: "SN", meanings: { upright: "直接、快速决断、带着目标冲向问题。", reversed: "急躁鲁莽、言语伤人、速度超过判断。" } },
  { id: "swords-queen", name: "Queen of Swords", zhName: "宝剑王后", image: "SQ", meanings: { upright: "清醒、边界、用成熟理性说出真话。", reversed: "过度冷硬、批判、防御心让关系难以靠近。" } },
  { id: "swords-king", name: "King of Swords", zhName: "宝剑国王", image: "SK", meanings: { upright: "理性权威、规则、清楚而有判断力。", reversed: "冷漠控制、逻辑压迫、缺少情感温度。" } },

  { id: "pentacles-ace", name: "Ace of Pentacles", zhName: "星币一", image: "P1", meanings: { upright: "现实机会、资源、可落地的新开始。", reversed: "机会延迟、资源不足、需要先确认现实基础。" } },
  { id: "pentacles-two", name: "Two of Pentacles", zhName: "星币二", image: "P2", meanings: { upright: "平衡、调度、同时处理多项现实事务。", reversed: "失衡、顾此失彼、需要减少手上的变量。" } },
  { id: "pentacles-three", name: "Three of Pentacles", zhName: "星币三", image: "P3", meanings: { upright: "协作、专业、把能力放进团队结构里。", reversed: "配合不顺、标准不一、专业价值没有被看见。" } },
  { id: "pentacles-four", name: "Four of Pentacles", zhName: "星币四", image: "P4", meanings: { upright: "保守、守住资源、需要安全感。", reversed: "过度抓紧、害怕失去、也可能开始学会放手。" } },
  { id: "pentacles-five", name: "Five of Pentacles", zhName: "星币五", image: "P5", meanings: { upright: "匮乏、压力、感觉自己缺少支持。", reversed: "援助出现、状况改善、愿意承认自己需要帮助。" } },
  { id: "pentacles-six", name: "Six of Pentacles", zhName: "星币六", image: "P6", meanings: { upright: "给予与接受、资源流动、公平分配。", reversed: "不平等交换、亏欠感、付出和回报失衡。" } },
  { id: "pentacles-seven", name: "Seven of Pentacles", zhName: "星币七", image: "P7", meanings: { upright: "等待收成、评估投入、耐心看长期结果。", reversed: "急于回报、投入方向存疑、需要调整策略。" } },
  { id: "pentacles-eight", name: "Eight of Pentacles", zhName: "星币八", image: "P8", meanings: { upright: "练习、打磨、通过持续投入提升能力。", reversed: "敷衍、重复劳动、努力没有对准成长方向。" } },
  { id: "pentacles-nine", name: "Nine of Pentacles", zhName: "星币九", image: "P9", meanings: { upright: "独立、丰盛、自我经营带来稳定成果。", reversed: "依赖感、表面体面、需要重建真正的自给能力。" } },
  { id: "pentacles-ten", name: "Ten of Pentacles", zhName: "星币十", image: "P10", meanings: { upright: "长期稳定、家族与资产、现实层面的圆满。", reversed: "结构松动、长期安全感受挑战、价值传承出现分歧。" } },
  { id: "pentacles-page", name: "Page of Pentacles", zhName: "星币侍从", image: "PP", meanings: { upright: "学习现实技能、务实开始、愿意慢慢积累。", reversed: "拖延实践、目标不够具体、纸上计划太多。" } },
  { id: "pentacles-knight", name: "Knight of Pentacles", zhName: "星币骑士", image: "PN", meanings: { upright: "稳定执行、负责、一步一步把事做完。", reversed: "停滞、固执、过度谨慎导致错过时机。" } },
  { id: "pentacles-queen", name: "Queen of Pentacles", zhName: "星币王后", image: "PQ", meanings: { upright: "滋养现实、照顾生活、温暖而务实的掌控力。", reversed: "过度操心、自我消耗、现实压力挤压感受。" } },
  { id: "pentacles-king", name: "King of Pentacles", zhName: "星币国王", image: "PK", meanings: { upright: "稳定成就、资源管理、成熟可靠的现实力量。", reversed: "物质执念、保守僵化、把安全感建立在控制上。" } },
];

export const tarotDeck: TarotCard[] = tarotCards.map((card) => ({
  ...card,
  imageUrl: rwsImageUrl(card.id),
}));
