#!/usr/bin/env node
require("child_process")
  .spawnSync("D:\\nodejs\\node.exe", ["D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js", ...process.argv.slice(2)], {
    stdio: "inherit",
    shell: false,
  });
