// ----------------------------------------------------------------
// AUTO-GENERATED — DO NOT EDIT
// System tables managed by EdgeSpark (auth, config, migrations).
// Regenerated by: edgespark pull schema
//
// Use these tables in JOINs and foreign keys from your own tables:
//   import { esSystemAuthUser } from "../__generated__/sys_schema";
//
// Your tables go in src/defs/db_schema.ts (code-first, not here).
// ----------------------------------------------------------------

import { relations } from "drizzle-orm/relations";
import { esSystemAuthUser, esSystemAuthAccount, esSystemAuthSession } from "./sys_schema";

export const esSystemAuthAccountRelations = relations(esSystemAuthAccount, ({one}) => ({
	esSystemAuthUser: one(esSystemAuthUser, {
		fields: [esSystemAuthAccount.userId],
		references: [esSystemAuthUser.id]
	}),
}));

export const esSystemAuthUserRelations = relations(esSystemAuthUser, ({many}) => ({
	esSystemAuthAccounts: many(esSystemAuthAccount),
	esSystemAuthSessions: many(esSystemAuthSession),
}));

export const esSystemAuthSessionRelations = relations(esSystemAuthSession, ({one}) => ({
	esSystemAuthUser: one(esSystemAuthUser, {
		fields: [esSystemAuthSession.userId],
		references: [esSystemAuthUser.id]
	}),
}));